name: smokedetector
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - category_encoders==2.6.3
    - cerberus
    - dotenv-cli
    - ensure==1.0.4
    - flask==3.0.3
    - flask-cors==4.0.1
    - flask-mail==0.10.0
    - joblib==1.4.2
    - matplotlib==3.9.0
    - numpy==1.26.4
    - pandas==2.2.2
    - pip-chill==1.0.3
    - python-json-logger
    - pymongo==4.7.3
    - python-box==7.2.0
    - python-dotenv
    - pyyaml==6.0.1
    - psycopg2==2.9.9
    - pytorch-lightning==2.4.0
    - requests==2.32.3
    - scikit-learn==1.5.0
    - seaborn==0.13.2
    - streamlit==1.36.0
    - toml==0.10.2
    - torch==2.2.0
    - types-pyyaml==6.0.12.20240311
    - tqdm==4.66.4
    - -e .  # Install your project in editable mode
