artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion 
  mongo_uri: "mongodb+srv://Minich:Mydatabase.456@minich-data-repository.gzlkk1s.mongodb.net/?retryWrites=true&w=majority&appName=Minich-Data-Repository"
  database_name: smarthome
  collection_name: smokedata
  batch_size: 20000
  slack_webhook_url: https://hooks.slack.com/services/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


